### ISSUE TITLE
cant figure out how to get to nether

### ISSUE THREAD

**Issue by rorykin5** [BluePsychoRanger/SkyBlock_Collection#14]
ive been playing for a bit and have no idea how im supposed to get to the nether at all

**Comment by BluePsychoRanger** [comment]
You'll need to generate lava to get to the nether. If you're playing One Block (from modrinth), the first lava can be obtained from the end portal, otherwise Standard Skyblock comes with the first lava. You'll need to obtain emeralds from villagers or foxes. Some foxes spawn with emeralds in their mouths and will drop their current item for food, or 8.5% chance upon death. Gold for golden apples can be obtained by striking pigs with lightning to convert them into zombie piglins which will drop gold upon death. Once you get emeralds you can buy pointed dripstone from wandering traders which can be used to generate lava. To generate lava, a source block must be above a pointed dripstone that's right above a cauldron; so the sequence of blocks from top to bottom is a lava source block, solid block, pointed dripstone, empty cauldron. 

I recommend joining the [discord](https://discord.gg/mzWSZuGatd) for further help as I answer there quicker and there are other sky block players that can help with progression

**Comment by rorykin5** [comment]
im playing the standard skyblock version (modrinth) ill join the discord for better help if i need it
