### ISSUE TITLE
FR: Removing 1.21 structures (experiments-enabled)

### ISSUE THREAD

**Issue by EvModder** [BluePsychoRanger/SkyBlock_Collection#19]
Is it possible to remove Trial Chambers (upcoming 1.21 experiment, available in current release during world creation)?

Understandable if support for this isn't planned until the next (full) major release, but would be awesome to have.

![Screenshot 2024-05-22 023839](https://github.com/BluePsychoRanger/SkyBlock_Collection/assets/5511002/186c097c-3da2-44cb-ae9d-e6f47f1096c9)

**Comment by offbeat-stuff** [comment]
In case you want to run the new 1.21 features, this might help:

https://modrinth.com/datapack/no-trial-chambers

This datapack give features of 1.21 without the trial chambers generating

**Comment by BluePsychoRanger** [comment]
There is no plan to support experimental features since I can't guarantee every experimental feature will be accounted for in the future. It's unsustainable for me since it requires extra work that I may not have time for, especially if things keep changing with those experimental features. If you download the datapack offbeat-stuff linked, you would get the 1.21 features without the trial chambers.

Alternatively, you can edit the datapack by navigating to the following folder:
`/data/minecraft/worldgen/structure_set` and duplicating the `trail_ruins.json` file and naming the duplicate file `trial_chambers.json`
