### ISSUE TITLE
Mineshafts in skyvoid_worldgen_structures_v1_0_1-MC_1_21 are now broken

### ISSUE THREAD

**Issue by dandud100** [BluePsychoRanger/SkyBlock_Collection#25]
>There was a bug with the chest minecarts. I've fixed it in Release 2.1.1 (`skyvoid_worldgen_structures_v1_0_1`). In the future, >please open a new issue so it doesn't get lost.
>
>_Originally posted by @BluePsychoRanger in >https://github.com/BluePsychoRanger/SkyBlock_Collection/issues/5#issuecomment-2386433476_

So, the minecarts are now there but not the wood planks below the tracks, also the chains are gone:
![2024-10-01_18 21 05](https://github.com/user-attachments/assets/10eb12b1-02d4-4319-86bb-2098b4b5dedd)

This was not the case on v1.0.0

**Comment by BluePsychoRanger** [comment]
The issue is that when mineshafts generate, the minecarts only generate if there's a solid block already there. But if there's a block already there, it doesn't generate the wooden platforms. I realized I could make some of the wooden platforms generate (by fixing a bug in how I let the world generate), but basically it's either "void friendly" structures or proper generation matching a normal world. Like in a normal world, the floor would be mostly the stone that generates as part of caves with some wood when the mineshaft realizes it's floating, so by fixing the minecart bug, it made the mineshafts generate how they would in a normal world: without those extra wood platforms. 

I'll push a fix with the cave generation so some of the wood platforms generate, but otherwise it is technically working as intended, since the mineshaft wouldn't generate with most of the wood platforms in a normal world.

**Comment by BluePsychoRanger** [comment]
Updated cave generation in Release 2.1.2 (skyvoid_worldgen_structures_v2_0_2), according to the message above.
